version: "3.9"

services:
  bbq-server:
    container_name: bbq-server
    build:
      context: ..
      dockerfile: deploy/Dockerfile.server
      args:
        NODE_IMAGE: ${NODE_IMAGE:-ccr.ccs.tencentyun.com/macho_bbq/node:18-bullseye-slim}
    env_file:
      - ./env/.env.server
    ports:
      - "3000:3000"
    volumes:
      - ./data/uploads:/app/apps/server/uploads
    restart: unless-stopped
