version: "3.9"

services:
  mysql:
    container_name: bbq-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-bbq_miniapp}
      TZ: ${TZ:-Asia/Shanghai}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - bbq_mysql_data:/var/lib/mysql
    networks:
      - bbq-net

  bbq-server:
    container_name: bbq-server
    image: ccr.ccs.tencentyun.com/macho_bbq/bbq-server:${TAG:-latest}
    depends_on:
      - mysql
    env_file:
      - ./env/.env.server
    volumes:
      - ./data/uploads:/app/apps/server/uploads
    restart: always
    networks:
      - bbq-net

  bbq-nginx:
    container_name: bbq-nginx
    image: nginx:1.25-alpine
    depends_on:
      - bbq-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./data/html:/usr/share/nginx/html:ro
    restart: always
    networks:
      - bbq-net

networks:
  bbq-net:
    name: bbq-net

volumes:
  bbq_mysql_data:
